name: 'Setup Edge'
description: 'Install and setup Microsoft Edge'
author: "Shin'ya Ueoka"
input:
  edge-version:
    description: |-
      The Edge version to be installed.  Supported versions are "stable", "beta", "dev"
    default: stable
    required: false
runs:
  using: 'node12'
  main: 'index.js'
