name: 'Setup Edge'
description: 'Install and setup Microsoft Edge'
author: "Shin'ya Ueoka"
inputs:
  edge-version:
    description: |-
      The Edge version to be installed.  Supported versions are "stable", "beta", "dev"
    default: stable
    required: false
outputs:
  edge-version:
    description: 'The installed Edge version. Useful when given a latest version.'
  edge-path:
    description: 'The installed Edge path.'
runs:
  using: 'node20'
  main: 'index.js'
