name: 'build-test'
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: yarn package
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/

  test:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: "Install default channel on ${{ matrix.os }}"
        uses: ./
      - name: "Install stable channel on ${{ matrix.os }}"
        uses: ./
        with:
          edge-version: stable
      - name: "Install beta channel on ${{ matrix.os }}"
        uses: ./
        with:
          edge-version: beta
      - name: "Install dev channel on ${{ matrix.os }}"
        uses: ./
        with:
          edge-version: dev
      - name: "Install canary channel on ${{ matrix.os }}"
        uses: ./
        with:
          edge-version: canary
        # Canary channel for linux is not currently supported
        if: ${{ matrix.os != 'ubuntu' }}

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'latest'
      - uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Setup git
        run: |
          git config --global user.name "Shin'ya Ueoka"
          git config --global user.email "ueokande@i-beam.org"

          cat >$HOME/.netrc <<EOF
          machine github.com
          login ueokande
          password ${GITHUB_TOKEN}
          EOF

      - name: Deploy to latest branch
        run: |
          # Abort job successfully when no scripts updated
          test -z "$(git status --short)" && exit 0

          git add .
          git commit --message "Release for ${GITHUB_SHA}"
          git push origin latest

  test-latest:
    runs-on: windows-latest
    needs: [deploy]
    steps:
      - uses: browser-actions/setup-edge@latest
